### ISSUE TITLE
Site Identity: Incorrect Favicon

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#1]
Description:

The Favicon on the site is incorrect

Favicon:
You can use the hand part of the logo':
![image](https://user-images.githubusercontent.com/75774252/155964391-dab6955a-7f7f-4dc1-af3a-0275a6528c89.png)

![image](https://user-images.githubusercontent.com/75774252/155964165-1610e625-8826-4d10-9753-06caf248fad1.png)

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155692269-a046553b-ca96-470c-9253-c3c0c61940a7.png)

**Comment by MamataNivajekar** [comment]
@EktaNaik please confirm If I should proceed with the above suggestion.

**Comment by EktaNaik** [comment]
@MamataNivajekar Yes, please use the 1st half part of logo (circle with hand) on transparent background instead of the default Genesis favicon. See below.
![image](https://user-images.githubusercontent.com/44566188/156108067-69af900b-db70-480c-b8ed-ccf86f25354c.png)

**Comment by MamataNivajekar** [comment]
noted

**Comment by ShivaniAjency** [comment]
Fixed
