### ISSUE TITLE
Home: Font size of banner subtext is incorrect

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#104]
Issue:
Font size of banner subtext is incorrect.
Current size - 22px; Required size as per design - 18px
Also, font weight of banner heading should be 700. It is currently 600.

Screenshot:
![image](https://user-images.githubusercontent.com/44566188/157847478-c49b0376-3e8f-4b1b-8dca-949c7f130026.png)

**Comment by ShivaniAjency** [comment]
Issue fixed
