### ISSUE TITLE
Bueno finance - About us page issues - Desktop

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#105]
### **ISSUES:**

1. The color of the primary CTA button on the navigation bar is incorrect. The CTA button color should be #009020
![image](https://user-images.githubusercontent.com/96518669/157860135-dfe85c21-5865-48a7-a0b9-ddce630e8f41.png)

2. Color of the heading text is incorrect. The text color should be #134E19
![image](https://user-images.githubusercontent.com/96518669/157863303-412f747b-0efe-4573-beb1-46d0fe59c26f.png)

3. Company's name in the footer is incorrect. It should be " Bueno Gig Credit Building Technologies Pvt Ltd." 
![image](https://user-images.githubusercontent.com/96518669/157865043-b296a989-965b-4572-8336-92b7120c37ad.png)

**Comment by ShivaniAjency** [comment]
Issue fixed
