### ISSUE TITLE
Bueno Finance - about us issues - mobile 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#106]
### **ISSUES:**

1. Color of the heading text is incorrect. It should be #134E19, and the font weight should be bold
![image](https://user-images.githubusercontent.com/96518669/157863690-97cd1ef5-0aae-4685-ae0c-b6ff82c90c22.png)

2. The font size for the sub heading is incorrect. It should be 18px
![image](https://user-images.githubusercontent.com/96518669/157863906-28b2273f-f727-4180-a7dc-aa7fc6c17c77.png)

3. The font size for all the employees names is incorrect. It should be 22px. Please change it across everyone's name
![image](https://user-images.githubusercontent.com/96518669/157864291-8477b204-bea0-4271-b2de-a19d7b5d3581.png)

4. The company's full name in the footer is wrong. The text should be "Bueno Gig Credit Building Technologies Pvt Ltd." 
![image](https://user-images.githubusercontent.com/96518669/157864626-8f97fef0-3c6f-4373-b1bc-770504aacea4.png)

5. The color for the CTA button for the dropdown is incorrect. It should be of the following color #009020
![image](https://user-images.githubusercontent.com/96518669/157865663-4dbd8964-0aef-4ed5-9071-b371f2fb7846.png)

**Comment by ShivaniAjency** [comment]
Issue fixed
