### ISSUE TITLE
Bueno finance - Homepage - Desktop 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#107]
### **ISSUES:**

1. Height of the top navigation bar is incorrect. The height should be 80px. Please make this change across all pages 
![image](https://user-images.githubusercontent.com/96518669/158105116-aa2ea679-2cf3-4b8b-9091-c081ff9399f0.png)
 
2. Color of the Primary CTA button on the top nav is incorrect. The color for the CTA should be #009020. Please make this change across all the primary CTA buttons
![image](https://user-images.githubusercontent.com/96518669/158105514-ed61d0c7-6c17-409f-ae34-d1ffb9e93cc9.png)

3. Padding between the header text and the body text under it is incorrect. The spacing should be 20px.
![image](https://user-images.githubusercontent.com/96518669/158105970-c0419c87-5d74-4e2b-bd71-9458f693c308.png)

4. The animation for the banner images on the homepage is sliding, which is incorrect. The animation should be fade in and fade out for all the images. 
![image](https://user-images.githubusercontent.com/96518669/158106116-36e35854-ec74-4aa9-86bc-3b3e6be58f60.png)

5. The globe size is incorrect. The globe should be larger in size and should be next to the "why Bueno finance" heading text. The size used for the globe in the design is width = 838 and height - 542. 
![image](https://user-images.githubusercontent.com/96518669/158106609-d030ffe6-d4d1-4c7f-b2cb-fa3f23117e86.png)

6. The low interest rates and end to end digital points icons should be aligned. 
![image](https://user-images.githubusercontent.com/96518669/158107032-45879658-911f-4424-a8af-7ca94c493158.png)

7. The font sizes for the stats are incorrect. The top font for the stats should be 24px (highlighted in red in the image), and the bottom font for the text under the stats should be 16px.  (highlighted in purple in the image)
![image](https://user-images.githubusercontent.com/96518669/158107352-8fb51814-c21d-4a10-b11d-46bbffebcd48.png)

8. The text for the stats point "Loans sanctioned" should be on one line
![image](https://user-images.githubusercontent.com/96518669/158107512-f3666ae8-cee7-4824-985f-6cba960e4638.png)

9. The carousel animation for the MoKredit app screens is incorrect. The animation should be like a 3D carousel, with the main mobile mockup frame being static, and the app screenshot keeps changing. 
I'm providing an example of how the carousel should work. http://www.webdesign-flash.ro/p/s3dcar/
Also the mobile mockup size shouldn't change. only the screenshot changes position and size. 
The screenshot should also change when the user hovers over the points mentioned on the left
![image](https://user-images.githubusercontent.com/96518669/158108196-d26295c2-2a61-47c0-8375-d17be2c192f5.png)

10. The company's full name in the footer should be on one line only. 
![image](https://user-images.githubusercontent.com/96518669/158108774-173a2af8-64b6-454b-b61c-567eb305620a.png)
 
11. The font weight for the legal information text in the footer is incorrect. The font weight should be montserrat - thin
![image](https://user-images.githubusercontent.com/96518669/158108984-9dd05b67-b1fc-43f4-8ebe-ee5aeb7fac01.png)

12. There should be no animation for the Bueno finance app screens
![image](https://user-images.githubusercontent.com/96518669/158169428-95f8c042-e07a-48af-9b91-273d98461757.png)

**Comment by siddeshKalangutkar** [comment]
Point 4 - Animation for globe has been put on hold
Point 8 - Ignored (For handling responsiveness text will go on text line)

**Comment by ShivaniAjency** [comment]
1) Done
2) Done
3) Done
**4) Oh hold**
5) Done
6) Done
7) Done
**8) Ignored (For handling responsiveness text will go on text line)
9) New Animation is pending to be picked**
10) Done
11)  Done

**Comment by ShivaniAjency** [comment]
10) As confirmed by @Saee1799 , The screens will be static and no animation is required for the section. @siddeshKalangutkar The image on the screen as per the design

**Comment by ShivaniAjency** [comment]
10) Issue fixed
