### ISSUE TITLE
MAC OS: Our customer testimonial: Improper space between the image and testimonial

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#109]
Description:

- There is less gap between the image and the testimonial slider
- As per the design it should be 99

Screenshot:
Design
![image](https://user-images.githubusercontent.com/75774252/158112655-387d5b19-1c0e-46fd-a790-f2628e214999.png)

site
![image](https://user-images.githubusercontent.com/75774252/158113110-22859484-03df-4778-a92c-186a29e12e6a.png)

**Comment by siddeshKalangutkar** [comment]
Fixed

**Comment by ShivaniAjency** [comment]
issue fixed
