### ISSUE TITLE
Bueno finance - Homepage - mobile view

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#110]
### **ISSUES:**

1. The body copy for the header should be in 3 lines, and the space between the body copy and the "why bueno finance" section should be 60px
![image](https://user-images.githubusercontent.com/96518669/158111958-dbae72ed-9d0b-40b8-b754-f87b9eb185af.png)

2. The animation for the MoKredit screenshots should be moving in a 3D carousel, (Link to a reference given in the Bueno finance - homepage - desktop issues). The mobile mockup frame size shouldn't change with the screenshots. 
![image](https://user-images.githubusercontent.com/96518669/158112190-733aeba2-b4e9-4c3f-9338-0c38c1e76e46.png)

3. Spacing between the Bueno finance app screens and the body text under it is incorrect. It should be 30px, and the spacing between the body text and the google play download button should be 30px. 
![image](https://user-images.githubusercontent.com/96518669/158112698-8d5651ba-fce6-4431-b01c-4999c0975f3c.png)

4. Space below the google play download button should be 70px. The spacing under it is incorrect. 
![image](https://user-images.githubusercontent.com/96518669/158113051-793a6b36-dcc7-486e-8e6d-6f6c52ed0359.png)

5. Top padding for the "why partner with us" heading text is incorrect. The top padding should be 40px
![image](https://user-images.githubusercontent.com/96518669/158113229-30f067fd-195b-4a13-bf56-8f658d34506d.png)

6. The background color for the "Take a test ride with us" section is incorrect. The background color should be white, without any box border, and the white box should have a left and right padding of 20px and top padding of 30px and bottom padding of   38px. 
![image](https://user-images.githubusercontent.com/96518669/158113632-fd50c0d8-64e1-4cee-bddb-a5b39620f637.png)

7. The partner company logos animation is too fast, and has a snapping effect. The animation should be smooth and a bit slower so users can read. 
![image](https://user-images.githubusercontent.com/96518669/158113887-12fad455-18a9-4044-96c3-1889430e6c6e.png)

8. The body text for the "Lending partners" should be in one line
![image](https://user-images.githubusercontent.com/96518669/158114238-93c4f688-3ee9-417f-8c67-39e66ec9204e.png)

9. The spacing between the company's full name and company's address is incorrect. The spacing should be 16px. 
![image](https://user-images.githubusercontent.com/96518669/158114428-ad0a36e9-559c-4df2-9a18-bdc117f32209.png)

**Comment by ShivaniAjency** [comment]
1) Fixed
**2) New animation is pending to be picked**
3) Bueno finance app screens and the body text under it is incorrect. It should be 30px. At present, it is 16+24 @siddeshKalangutkar 
4) Done
5) Done
6) Background color issue fixed. Button is misaligned @siddeshKalangutkar 
![image](https://user-images.githubusercontent.com/75774252/158531888-0b2c53de-8269-44c3-aa8c-422295288d36.png)

7) Issue fixed
8) Issue prevails @siddeshKalangutkar 
9) Issue fixed

**Comment by siddeshKalangutkar** [comment]
@ShivaniAjency  Points: 3, 4, 7 - Done

**Comment by ShivaniAjency** [comment]
Issue fixed.

Our customers should be center aligned @siddeshKalangutkar 
![image](https://user-images.githubusercontent.com/75774252/158623897-d9acdbf9-aade-41c5-8a00-20fb5f62dd66.png)

**Comment by siddeshKalangutkar** [comment]
Fixed

**Comment by ShivaniAjency** [comment]
Issue fixed
