### ISSUE TITLE
Career page: incorrect image dimension

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#111]
Description:
The image dimension should be 600*363

Screenshot:
Site
![image](https://user-images.githubusercontent.com/75774252/158115700-dc7e7322-e940-4efc-8ee9-59414a45bf45.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/158115794-569f2482-c083-4624-8fe8-5c6072d115a0.png)

**Comment by siddeshKalangutkar** [comment]
Responsive size has been given to the image.
Heading color changed

**Comment by ShivaniAjency** [comment]
Noted
