### ISSUE TITLE
Bueno finance - Careers page - desktop 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#112]
### ISSUES:

1. Header text color is incorrect. The text color for the heading should be #134E19. 
![image](https://user-images.githubusercontent.com/96518669/158115735-03f9373b-9f07-4bfb-a19b-d371370c0819.png)

2. Apply on linkedin button is missing for the job applications
![image](https://user-images.githubusercontent.com/96518669/158116690-4a872c79-2aa3-4bc3-80f1-3a2dd9f5767b.png)

3. When the user tries to open another job description, the currently open description should close. (functionality)
Both shouldn't be open at the same time
![image](https://user-images.githubusercontent.com/96518669/158116886-01bc6739-9c26-48cb-83fe-236425a30025.png)

4. There is a line between the footer data and the legal information mentioned in the footer. Please remove that line
![image](https://user-images.githubusercontent.com/96518669/158117188-699fcc5c-ffd9-43de-9fda-6d082d197835.png)

5. In the submit application form the position text color is incorrect. The color should be #747474, to signify the users cannot change it on the form. 
![image](https://user-images.githubusercontent.com/96518669/158120260-d6c64c3a-22b8-4bdd-bcb0-cb5d247a8ec3.png)

**Comment by EktaNaik** [comment]
@ShivaniAjency Point 3 is not needed. Functionality is fine as is.

**Comment by ShivaniAjency** [comment]
Issue fixed. 

Kindly ignore the issue 5 raised by @ShivaniAjency
