### ISSUE TITLE
Bueno finance - Careers - mobile view 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#113]
### **ISSUES:**

1. The icon size for the "why work @ Bueno finance" section points is incorrect. The icons should be around 40 px in width and height. 
![image](https://user-images.githubusercontent.com/96518669/158118429-4d36650c-1bb1-4649-a3e0-0e0d2a7fe293.png)

2. The dropdown arrows for the opportunities section are placed incorrectly. They should be pointing down when the sections are closed and pointing up when the sections are open
![image](https://user-images.githubusercontent.com/96518669/158118750-fe7a7906-12b0-43a2-81e5-6058684db149.png)

3. The text color and the font weight for the opportunities dropdown text is incorrect. The text color should be #134E19 and the font weight should be semibold
![image](https://user-images.githubusercontent.com/96518669/158119066-631f3205-9e7a-4982-8ce5-47d835d61798.png)

4.  The apply on linkedin button is missing under the job application button 
![image](https://user-images.githubusercontent.com/96518669/158119240-2a55db59-ee83-4c88-bc7a-9d7c5fb41905.png)

**Comment by siddeshKalangutkar** [comment]
The linked In button will appear on adding link in the backend

**Comment by MamataNivajekar** [comment]
@ShivaniAjency 
Height of the last icon is incorrect --> width is same for all icons i.e 40px. if we set a fixed height for the icons it will look stretched
The apply on LinkedIn button is missing under the job application button --> duplicate issue #85

**Comment by ShivaniAjency** [comment]
Noted
