### ISSUE TITLE
Partner with us page - Desktop 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#114]
### **ISSUES:**

1.When you go to enter the phone number, a line appears on the input field, which is not required. 
![image](https://user-images.githubusercontent.com/96518669/158121257-743fccdd-2183-4918-a8dc-780a8fa5e8a8.png)

2. On submitting a form, the new empty form which appears now has a line missing under the company name and where did you hear about us section
![image](https://user-images.githubusercontent.com/96518669/158121427-4068faab-52f2-4752-aeef-241898c8a8a0.png)

3. The forward arrow user for the breadcrumb looks weird. You can export the one used in the design and use it in place of this one. Also the left and right padding for the arrow should be 14px.
![image](https://user-images.githubusercontent.com/96518669/158121863-c32a5bcd-28d8-49a7-a809-c6f10e6c9669.png)

4. The height for the map should be 320 px. 
![image](https://user-images.githubusercontent.com/96518669/158122130-b5f5305c-81a9-4c61-bc6f-12bf98dda4c5.png)

5.  The bottom padding for the send button should be 60px and the height of the form section should be more than the height of the entire map + address section.
![image](https://user-images.githubusercontent.com/96518669/158122248-a155c741-0bba-4dc9-b10b-8d0f2575a126.png)

**Comment by MamataNivajekar** [comment]
1. done
2. done @Saee1799 @ShivaniAjency (ping me before testing this issue, we have added the client's mail id as a notification receiver)
3. done
4. done
5. The bottom padding for the send button should be 60px and the height of the form section should be more than the height of the entire map + address section. --> @Saee1799  padding-bottom is already set to 60px for the overall section & we cannot set a fixed height for the form section it depends on the content inside the section.

**Comment by ShivaniAjency** [comment]
1) Fixed
2) Fixed
3) Fixed
4) Fixed
5) Not an issue
