### ISSUE TITLE
Home: Our partners logo testimonial: logos are appearing blurry

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#115]
Description:

- The logos in the section are appearing blurry
- First Meridian logo is getting cropped

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/158124840-c318e68a-569f-4ce4-a568-73e446fc7686.png)
![image](https://user-images.githubusercontent.com/75774252/158518184-f6f5c79c-bf34-4d45-9e78-ed9b120ea9bc.png)

**Comment by siddeshKalangutkar** [comment]
Higher resolution images need to be uploaded.
Export the logo image from design with '2x' or '3x'.

The first meridian image is cropped in design.
