### ISSUE TITLE
Partner with us page - mobile 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#116]
### **ISSUES:**

1. The bottom padding for the "Partner with us" header text is incorrect. The bottom padding should be 20px 
![image](https://user-images.githubusercontent.com/96518669/158139306-9f67cf9a-5f24-47b0-a5fb-0bcbf4d08cc5.png)

2. Space between the Company's full name and the address text is incorrect. The spacing between them should be 20px  
![image](https://user-images.githubusercontent.com/96518669/158139570-b93075ef-0591-4d67-9f03-660cbf8417c9.png)

3. The dropdown options in the form are still dummy text. Please enter valid inputs for the dropdowns
![image](https://user-images.githubusercontent.com/96518669/158139961-0c218201-f09e-4b12-b86e-545732aa8fa3.png)

4. Space between the send button and the footer is incorrect. The space should be 40px 
![image](https://user-images.githubusercontent.com/96518669/158140464-279a916f-fe7a-4b1b-8705-133cb3a62117.png)

5. In the mobile footer, the space between the Company's full name and the address is incorrect. The space between them should be 16px. (please make this change across all the mobile footers)
![image](https://user-images.githubusercontent.com/96518669/158140877-805cbc63-0f21-487f-9cf9-09528a6c2999.png)

6. In the mobile footer, right padding for the helpful links section is too large, The right padding for the entire part should be 33px
![image](https://user-images.githubusercontent.com/96518669/158141295-988d7bcb-6db1-4faa-b39a-8cc6909dba72.png)

7. For the hamburger menu, the center line looks thinner than the top and bottom lines, please give them the same thickness
![image](https://user-images.githubusercontent.com/96518669/158141804-965a51f0-efc8-472e-9e72-35b9c5150916.png)

8. Partner with us - heading text color should be #134E19 color

**Comment by ShivaniAjency** [comment]
Issues 1 to 5 and 8 are fixed
7) all three lines has the same thickness i.e 1.5px and line height
