### ISSUE TITLE
FAQ page - Desktop 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#117]
ISSUES:

Spelling mistakes

1. FAQ 1: spelling of MoKredit is wrong, they have the K in capital for the MoKredit app name
![image](https://user-images.githubusercontent.com/96518669/158143482-9f279a97-eab2-44e2-822a-892a70ace847.png)

2. FAQ 3: spelling of MoKredit is wrong, they have the K in capital for the MoKredit app name
![image](https://user-images.githubusercontent.com/96518669/158143704-440b285c-191c-45d0-a3cc-28d4808fbd80.png)

3. FAQ 6: spelling of MoKredit is wrong, they have the K in capital for the MoKredit app name
![image](https://user-images.githubusercontent.com/96518669/158143953-e4a534c9-bf57-4e8e-b30b-5c94fb54663d.png)

4. FAQ 7: spelling of MoKredit is wrong
![image](https://user-images.githubusercontent.com/96518669/158144282-7a74318a-0978-4f11-b037-fc09574d71e7.png)

5. FAQ 8:  spelling of MoKredit is wrong
![image](https://user-images.githubusercontent.com/96518669/158144398-b1607350-f517-4d4e-8383-a8c619cc7d51.png)

6. Bottom spacing for the body copy under the heading is incorrect. The spacing should be 60px
![image](https://user-images.githubusercontent.com/96518669/158144848-ea802351-73a9-4de5-8aef-e3175531e913.png)

7. Top spacing for the page header is incorrect, it should be 30px 
![image](https://user-images.githubusercontent.com/96518669/158144992-44c9a0e9-0086-4f60-9c44-81aa479096bb.png)

**Comment by EktaNaik** [comment]
@MamataNivajekar all page headers should have the same spacing - padding/margin. Hence set the spacing accordingly.

**Comment by MamataNivajekar** [comment]
@EktaNaik all the page headers have the same padding @ShivaniAjency you can check [here](https://buenofinance.dreamhosters.com/privacy-policy/).

**Comment by ShivaniAjency** [comment]
As mentioned by @EktaNaik and as clarified by @MamataNivajekar all the page headers have the same padding
