### ISSUE TITLE
Privacy policy page 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#118]
ISSUES:

1. No indentation is provided for point number 2 and point 5 
![image](https://user-images.githubusercontent.com/96518669/158150412-183121d5-fec3-463c-b423-f01e52e242bc.png)

![image](https://user-images.githubusercontent.com/96518669/158150495-1701b42e-9512-4adb-be83-a9c194bbb20e.png)

**Comment by ShivaniAjency** [comment]
Issue fixed
