### ISSUE TITLE
MoKredit- Scan, Pay and Loan : Incorrect height for the title

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#12]
**Description:**

The height for the title in the design 44px whereas on the live is 48px

**Screenshot:**
1) Site

![image](https://user-images.githubusercontent.com/75774252/155719065-060ee505-aae0-4577-997f-a719fdc6cd0f.png)

2) Design

![image](https://user-images.githubusercontent.com/75774252/155719122-1d7e3ef5-6d99-4566-9710-92d57fe57551.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency the font size & line-height is same as per the design. 
![image](https://user-images.githubusercontent.com/81617777/156108981-69e9038f-8e99-4c94-b6cb-6b2e8c34f20c.png)

**Comment by ShivaniAjency** [comment]
Noted
