### ISSUE TITLE
Homepage - desktop

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#120]
Issues:

1. The spacing between the icons and the points is incorrect. The spacing should be 30px 
![image](https://user-images.githubusercontent.com/96518669/158169914-d49a77b5-0a6d-49c0-88bb-5cb6d2542161.png)

**Comment by siddeshKalangutkar** [comment]
Fixed

**Comment by ShivaniAjency** [comment]
Issue fixed
