### ISSUE TITLE
Bueno Finance- Personal Loan and Instant Cash-  Incorrect height for the title and subtitle

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#17]
**Description:**
Incorrect height. 

_Title:_
The height in the design is 44px whereas on the site it is 48px

_Subtitle:_
The height in the design is 37px whereas on the site it is 28px

**Screenshot:**
_For Title_
1) Design
![image](https://user-images.githubusercontent.com/75774252/155923366-326b0d18-c6d9-4974-a479-ec9f145942a1.png)

2) Site:
![image](https://user-images.githubusercontent.com/75774252/155923552-2a5f47cd-f132-4fc1-9fd8-e481c2975777.png)

For Subtitle:
1) Design

![image](https://user-images.githubusercontent.com/75774252/155924033-c61fe6d2-44d0-4823-8dc3-b0d45bc397ee.png)

2) Site:

![image](https://user-images.githubusercontent.com/75774252/155924204-c082c172-afa6-46ec-bb68-bec580d2d673.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency please check font size & line-height, it's the same as per the design.
![image](https://user-images.githubusercontent.com/81617777/156110807-ce3430e2-9de9-492d-91b2-1950502fe5da.png)
![image](https://user-images.githubusercontent.com/81617777/156110889-64c2eed6-af24-4467-a926-116616f83338.png)
![image](https://user-images.githubusercontent.com/81617777/156110994-a15c162d-01aa-459c-b709-12af4e02401f.png)
