### ISSUE TITLE
Site Identity: Incorrect site name

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#2]
**Description:**

Currently, the site name is getting displayed as
"Bueno Finance – Just another WordPress site"

![image](https://user-images.githubusercontent.com/75774252/155701837-bbebd27d-63ac-431d-badf-a48a7993c677.png)

**Correction:**
The correct site name would be "Bueno Finance"

**Comment by MamataNivajekar** [comment]
@ShivaniAjency site title was correct. I have removed the default WordPress tagline.
![image](https://user-images.githubusercontent.com/81617777/156103818-9f7501e4-c4c9-4cf7-ad9b-3b49bfc75f68.png)

**Comment by ShivaniAjency** [comment]
Fixed
