### ISSUE TITLE
Footer: Missing hyperlinks for quick menu

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#28]
Description:
Hyperlinks are missing for the menu items under the quick menu

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155930575-547446fa-ce9b-4674-b363-6967c31feac7.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency pages are not created yet

**Comment by ShivaniAjency** [comment]
Invalid bug
