### ISSUE TITLE
Footer: Missing hyperlinks for Helpful menu

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#29]
Description:
1) Spelling mistake. It should be 'Helpful' (Highlighted in yellow)
2) Hyperlinks are missing for the menu items under the helpful menu (marked in red)

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155930987-dd6fe36c-60d2-470c-a2c0-f8801f2a4300.png)

**Comment by MamataNivajekar** [comment]
1. done

**Comment by MamataNivajekar** [comment]
@ShivaniAjency pages are not created yet.

**Comment by ShivaniAjency** [comment]
1) Done
2) Invalid bug
