### ISSUE TITLE
Footer: Missing Hyperlinks Start a Dialogue menu

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#30]
Description:
1) Missing mailto tag
2) Missing tel tag
3) Missing hyperlinks

Screenshots:
![image](https://user-images.githubusercontent.com/75774252/155931338-32c79e26-a989-4fd7-b04a-9b94081fd628.png)

**Comment by MamataNivajekar** [comment]
1. & 2. -->  link updated

**Comment by MamataNivajekar** [comment]
@ShivaniAjency I don't have social media links except the 1. & 2. , If you found links related to the above issue please share in the comment or issue description.

**Comment by ShivaniAjency** [comment]
Linkedin:
https://in.linkedin.com/company/bueno-finance

YouTube
https://www.youtube.com/channel/UCB_IbQIOgx8490fGjWyNwPA/featured?view_as=subscriber

**Comment by MamataNivajekar** [comment]
@ShivaniAjency updated LinkedIn url
