### ISSUE TITLE
Mweb:Bueno Finance- Personal Loan and Instant Cash: Get it on google play not linked

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#38]
Description:
The 'Get it on google play button is not linked'

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155942944-3afa5fd2-2357-40ed-900d-c4b0f6f6e95f.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency we don't have links. If you have links related to the above issue please share in the comment.

**Comment by ShivaniAjency** [comment]
@MamataNivajekar  Please find the link here

https://play.google.com/store/apps/details?id=com.app.buenofinance&hl=en_IN&gl=MS

**Comment by ShivaniAjency** [comment]
Fixed
