### ISSUE TITLE
Mweb: Footer: Social media icons are not linked

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#40]
Description:
Social media icons are not linked.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155943910-d993e95f-8d9b-4721-9b81-de7aa6a1f032.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency  I don't have social media links except for the 1st & 2nd link, If you found links related to the above issue please share in the comment or issue description.

**Comment by ShivaniAjency** [comment]
LinkedIn link updated. Yet to receive confirmation about Twitter handle
