### ISSUE TITLE
Why Partner with us: Incorrect icon dimensions

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#43]
Description:
The marked images have incorrect dimensions. Please find the image dimensions below:

1) 62x61
2) 58x59
3) 58x58

![image](https://user-images.githubusercontent.com/75774252/155983988-ae37e8a9-c87d-44fe-a5f8-9585041617cc.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency to make icons alignment proper, I have added the same width for all icons i.e 60px
@EktaNaik let me know if the above suggestion is required.
![image](https://user-images.githubusercontent.com/81617777/156125112-384349ed-97aa-4dce-bddc-582a2dddef21.png)

**Comment by EktaNaik** [comment]
@MamataNivajekar can be ignored.

**Comment by ShivaniAjency** [comment]
Noted
