### ISSUE TITLE
Mweb: Why Partner with us : Section Does not match with design

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#44]
Description:

1) Why Partner with us Section looks broken on the mobile phone
2) The section on the site is different from the design
a) Icons size is incorrect. it should be 62x61
b) Icon placement is incorrect
c)The box for the CTA is missing. The background color and the box border is missing.
d) Button color for "Book a demo" is blue. It should be #134E19
e) CTA text should be center alighned.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/155984919-10110f90-07c5-4a70-975c-cc64bf5aa4dd.png)

![image](https://user-images.githubusercontent.com/75774252/155984978-1afbe056-0924-40f5-b96e-9fcd9dc3e0ad.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Please try to check in incognito.

**Comment by ShivaniAjency** [comment]
Initially had checked twice. The issue still prevailed.

The mobile design matches with the design
