### ISSUE TITLE
IOS Mobile: Hero banner section UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#45]
Description:

1) Hero image slider speed is too fast. 
2) The text gets cropped on the screen
3) Slider image does not get displayed at the center

Screenshots:
![image](https://user-images.githubusercontent.com/75774252/156105805-43520f38-212b-4908-9a8f-22c49e0fb4e7.png)

You can also refer:
https://www.awesomescreenshot.com/video/7647075?key=700277205f5125e2f0c117f5bd3f0db0

**Comment by MamataNivajekar** [comment]
@ShivaniAjency couldn't replicate the issue, please check the below screenrecord.

iPhone 11 v14

https://www.awesomescreenshot.com/video/7653907?key=c2d7659bc4e70567f78c9071b4f4bd93

**Comment by ShivaniAjency** [comment]
@MamataNivajekar This issue was seen on iPhone 8 v13.2

![image](https://user-images.githubusercontent.com/75774252/156304184-bc3db962-89d1-40a3-a02d-55b19380dfe5.png)

Screen recording:
https://www.awesomescreenshot.com/video/7668957?key=aa36bbebb0451826789b376102ed3984

**Comment by ShivaniAjency** [comment]
Fixed
