### ISSUE TITLE
IOS Mobile: Pre-footer: Lending partners : Section is not responsive

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#48]
Description:

Section is not responsive
1) Title and description get cropped
2) On scrolling horizontally through title and description appears the background gets cropped

**Screenshot:**
![image](https://user-images.githubusercontent.com/75774252/156110095-38ba33f2-9fb3-41c6-bb8c-9dd035f6103f.png)

![image](https://user-images.githubusercontent.com/75774252/156110248-8904ff17-18f7-4947-bac8-d598bb303eaf.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency couldn't replicate the issue. Please check the below screenshot.

iPhone 11 v15.1

![image](https://user-images.githubusercontent.com/81617777/156159722-3b540587-fcef-4494-a815-550a8eba58eb.png)

**Comment by ShivaniAjency** [comment]
The site is appearing fine
