### ISSUE TITLE
Add hover animation to Anchor Texts

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#49]
**Description**:

- Add hover animation to all Anchor Texts specially header and footer menu tabs.
- On-hover of tab display text underline same as font color.

Animation reference - https://www.30secondsofcode.org/css/s/hover-underline-animation

Screenshot - 
![image](https://user-images.githubusercontent.com/44566188/156110277-dec6e80a-75aa-406e-95ec-88e3ec7e8982.png)

**Comment by ShivaniAjency** [comment]
The enhancement is working fine
