### ISSUE TITLE
IOS Mobile: Pre footer: our backing: Section is not responsive

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#50]
**Description:**

The section is not responsive

1. Title and description get cropped
2. On scrolling horizontally through title and description appears the background gets cropped

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156110394-4b4dfb96-389e-47f9-9f02-6d8efdd45d6c.png)
![image](https://user-images.githubusercontent.com/75774252/156110476-5f86e338-9ec6-4e4c-b3e6-ce8b4520ecee.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency couldn't replicate the issue. Please check the below screenshot.
iPhone 11 v15.1
![image](https://user-images.githubusercontent.com/81617777/156159390-ace38718-a523-45d4-868c-0852b0162d57.png)

**Comment by ShivaniAjency** [comment]
The section is appearing fine
