### ISSUE TITLE
Add hover animation to all buttons

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#51]
**Description**:

- Add hover animation to all buttons
- On-hover, button color should fade as it does for Book a Demo button.

Screenshot -
![image](https://user-images.githubusercontent.com/44566188/156112861-94b26b21-c4e5-432b-a3e1-b5ca87b5b2f4.png)

**Comment by ShivaniAjency** [comment]
Enhancement working fine
