### ISSUE TITLE
TAB:Chrome: Pre-footer: Leading partner And Our Backing: Line height issue for the logo carousel

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#58]
Description:
The logo carousel are not in the same line

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156310620-416cd0e7-e6f5-4315-9db7-f4c4c291bdbd.png)

**Comment by ShivaniAjency** [comment]
The logo should be vertically center aligned. This issue was seen in Tab: 249x163

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Couldn't replicate the issue.

Testing device: Samsung Galaxy S4 v8.1

https://www.awesomescreenshot.com/video/7758880?key=e5bb8f7e3245a8974959ded27c7953fd

**Comment by ShivaniAjency** [comment]
Tested on an actual device. Works fine
