### ISSUE TITLE
TAB: Chrome MoKredit- Scan, Pay and Loan: The third image in the carousel is touching the background border

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#59]
Description:
The third image in the carousel is touching the background border whereas per the design there should be some space between them too

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/156311237-12b0d506-9a41-4157-934e-6d9672bc64ff.png)

**Comment by ShivaniAjency** [comment]
The dimensions were 245x160x5.5mm, Device: galaxy tab Se5

**Comment by MamataNivajekar** [comment]
@ShivaniAjency couldn't replicate the issue. The rows are converted into column direction on tablets.

tested using the above dimensions: 245x160x5.5mm i.e 925x604px

![image](https://user-images.githubusercontent.com/81617777/157382482-4af4f33a-dcf4-48b9-89fd-fe4443589619.png)

**Comment by ShivaniAjency** [comment]
invalid issue. The issue was not repeated when tested on an actual tab
