### ISSUE TITLE
MAC book air: UI Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#61]
Description:

1. Header banner carousel, UI is broken
2. MoKredit- Scan, Pay and Loan section is broken
3. Bueno Finance- Personal Loan and Instant Cash
4. Our Backing Cannot be seen on the screen

Screen recording:
https://www.awesomescreenshot.com/video/7648011?key=f495abf3e87d7ef00b85c6d7ee57b6a5

**Comment by MamataNivajekar** [comment]
fixed by @siddeshKalangutkar

**Comment by ShivaniAjency** [comment]
1,2 3, --> Done

The logos in the carousel should be vertically center aligned
![image](https://user-images.githubusercontent.com/75774252/156701709-2f89ce6d-67f6-4d7e-9832-c01a60b15149.png)

**Comment by ShivaniAjency** [comment]
Fixed
