### ISSUE TITLE
Partner with us:  Map Issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#67]
Description:

1. The location pointer on the site is red in color whereas on the design it's black and white
2.  As per the design the address box shouldn't get displayed on the map 

Screenshot:
Site
![image](https://user-images.githubusercontent.com/75774252/156723728-4254bd5d-e0f7-484c-9284-2322b0f1e652.png)
Design:
![image](https://user-images.githubusercontent.com/75774252/156721986-ea30df09-d1f4-4d82-a011-00481cc04ec3.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency As we discussed in the group chat, Map customization requires a "Maps JavaScript API key" with a billing account enabled. Since this feature is paid we have decided to keep the default map styles.

**Comment by ShivaniAjency** [comment]
Noted
