### ISSUE TITLE
Partner with us: Contact form issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#69]
Description:

1. The label is missing for the email id field
2. Name field is not authenticated
3.  The background color of the form fields  #F2FFEF;

screenshot:
![image](https://user-images.githubusercontent.com/75774252/156725663-b9ed7b42-7f4a-4d36-b043-b5eedbc18efe.png)

![image](https://user-images.githubusercontent.com/75774252/156725995-acae25c1-0497-4736-9e87-e7cd1f86ee0d.png)

**Comment by MamataNivajekar** [comment]
1. done
3. done

@ShivaniAjency usually the name field allows the numbers, you can check the other job application [forms](https://ajency.in/task-for-backend-developer-nodejs/). @EktaNaik please let me know if the 2nd point is required.

**Comment by EktaNaik** [comment]
@MamataNivajekar This can be ignored. Name field can accept any values.

**Comment by ShivaniAjency** [comment]
Fixed
