### ISSUE TITLE
Home - Why Bueno Finance : Ratio of columns is incorrect

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#71]
**Description**:

- Ratio of columns is incorrect for the Why Bueno Finance section
- It should be 1:2 whereas it currently is 1:1 ratio.
- Because of this the 4 number blocks UI looks broken.

**Screenshots**:
Design
![image](https://user-images.githubusercontent.com/44566188/156762477-728ae5be-bb68-4ae6-a77d-ab414600faa5.png)

Site
![image](https://user-images.githubusercontent.com/44566188/156762516-73ac6f96-5296-4668-bfaf-8342d3f528e2.png)

**Comment by ShivaniAjency** [comment]
Fixed
