### ISSUE TITLE
Home - MoKredit: Icons text alignment is incorrect

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#72]
**Description**:

- Icons text alignment is incorrect
- Text needs to be vertically center-aligned wrt the icons.

Screenshots:
Design
![image](https://user-images.githubusercontent.com/44566188/156762979-7b75cf2b-e577-4963-bf65-e143a1f87c6a.png)

Site
![image](https://user-images.githubusercontent.com/44566188/156763049-f728cbde-f168-42a7-9b65-bce60adfc09b.png)

**Comment by ShivaniAjency** [comment]
Fixed
