### ISSUE TITLE
Home - Bueno Finance: Margin-bottom missing for paragraph text

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#73]
**Description**:

- Margin-bottom missing for paragraph text
- Add margin-bottom: 33px for the paragraph text
- Currently the text is almost touching the QR code below.

Screenshot:
![image](https://user-images.githubusercontent.com/44566188/156764662-b8022963-fa66-4833-9cb8-970cf66d61d7.png)

**Comment by ShivaniAjency** [comment]
Fixed
