### ISSUE TITLE
About us : The Team: The section does not have margin-left property

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#75]
Description:
The margin-left property on the site is 2rem 
![image](https://user-images.githubusercontent.com/75774252/156966407-94ca1da3-d7a6-47d3-b7e7-7bc8ac9d78d5.png)
 
whereas in the design this property is not mentioned
![image](https://user-images.githubusercontent.com/75774252/156966526-b34673d6-7972-40a6-b104-c3159c1545dc.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency updated the margin-left with 22px (as per the design)

**Comment by ShivaniAjency** [comment]
Fixed
