### ISSUE TITLE
Career page : Why work @Bueno Finance

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#78]
Description:

1. Content and icons to be updated by @ShivaniAjency 
2. Alignment of icon text is not proper
3. Icon alignment is not proper

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157180525-7876ab64-2076-453a-985c-7821d59433f3.png)
![image](https://user-images.githubusercontent.com/75774252/157180698-d19ce983-678e-49b3-8beb-70f6cd0cdb1c.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency @ShivaniAjency 
1) alignment of icon text is proper you can check the below screenshot.
![image](https://user-images.githubusercontent.com/81617777/157245492-58731f3b-cad5-4efa-9d16-6fa0fa148792.png)

2) for icon alignment I have set all icon width: auto & height: 79.05px (height as per the first icon in the design)

**Comment by ShivaniAjency** [comment]
Fixed
