### ISSUE TITLE
Career : Opportunities : Horizontal tab:  Incorrect font weight

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#79]
Description:
The font-weight of inactive tabs should 400. Currently, on-site, it is 600

Screenshot:

Site
![image](https://user-images.githubusercontent.com/75774252/157183293-e05c3648-c32e-4963-aa6f-438e44bf5d4e.png)

Design
![image](https://user-images.githubusercontent.com/75774252/157183481-cad86cd4-6cf7-4343-923c-2d48ff14123c.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency  I have changed the font-weight to 600 to avoid flickering during the hover state.

https://www.awesomescreenshot.com/video/7790970?key=7ad7546635a854346106fcb6e9728864

**Comment by ShivaniAjency** [comment]
Noted
