### ISSUE TITLE
Career: Opportunities accordian ( When NOT selected): Margin-top and Margin left is missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#80]
Description:

- Magin-top and Margin-left properties are missing
- They should be 30px as per the design

Screenshot:
Design
![image](https://user-images.githubusercontent.com/75774252/157185279-a64dbcc2-1071-478e-ae58-6a48f72a6c78.png)

Site:
![image](https://user-images.githubusercontent.com/75774252/157185938-f0cd743d-5c98-46f7-83cb-c4e11116d426.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency It's padding, not a margin & it's set to 30px as per the design.

![image](https://user-images.githubusercontent.com/81617777/157374793-9fcaf848-8780-4750-b703-5dd648e1afcb.png)

**Comment by ShivaniAjency** [comment]
Noted
