### ISSUE TITLE
Career: Opportunities accordian ( When NOT selected): Incorrect font color, margin and weight

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#81]
Description:

- The font color is the same as the icon color on the site.
- As per the design it should be background: #000000;
- The font-weight should be 400
- Margin bottom should be 30px

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157187419-b94a1669-d7e7-41b2-b60e-3d0d6cb347c7.png)

![image](https://user-images.githubusercontent.com/75774252/157187653-eacc683b-da87-4b09-8ada-cf3d7eec6db2.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency 

As per the design it should be background: #000000; --> done

The font-weight should be 400 --> font-weight is normal i.e 400

![image](https://user-images.githubusercontent.com/81617777/157376833-cceb1c03-1f76-4e8b-b818-246400f36b34.png)

Margin bottom should be 30px --> accordion header padding is 30px only (as per the design)

![image](https://user-images.githubusercontent.com/81617777/157376696-eac62419-45a8-41d0-9de2-426e6d836370.png)

**Comment by ShivaniAjency** [comment]
Done
