### ISSUE TITLE
Career: Opportunities accordian ( When NOT selected): Show more button margins

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#82]
Description:
Show more button margins as per design are as follows

- Top: 66
- Right: 69
- Bottom: 56

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157188498-051122b0-fcef-4396-a8a9-3997f7a58385.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency as per the design the "show more" button should be vertically center aligned to the accordion header we should not add fixed top, right, bottom values for it.

**Comment by ShivaniAjency** [comment]
Noted
