### ISSUE TITLE
Opportunities accordian  ( When  selected): Margin and font weight issues

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#84]
Description:

- Magin-top and Margin-left properties are missing
- They should be 30px as per the design
- The font-weight should be 400
- Margin bottom should be 30px

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157192582-d0e09a7f-b9b4-456b-9633-1c8fa5506f7e.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency 
Magin-top and Margin-left properties are missing --> properties are not missing its 30px. you can check accordion header properties.

![image](https://user-images.githubusercontent.com/81617777/157377760-7509d8ff-9f60-4a20-8d58-a3733e55600e.png)

The font-weight should be 400 --> font-weight is normal i.e 400 

![image](https://user-images.githubusercontent.com/81617777/157377883-b18f1008-df37-419a-b39c-490c3a8c86a2.png)

**Comment by ShivaniAjency** [comment]
noted
