### ISSUE TITLE
Apply on LinkedIn button missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#85]
Description:

- Apply on LinkedIn button is missing
- The same issue has been seen in mobile and ios

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157194696-18e28753-db2f-44e9-96e1-e5029ee4df18.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157194784-cdecd850-052f-4675-b1dd-cf050b08939a.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Apply on LinkedIn button is missing --> button will be visible if you add LinkedIn URL from the page backend.

page backend:

![image](https://user-images.githubusercontent.com/81617777/157378556-c04de60a-be68-4db8-85a4-a20970376c2b.png)

**Comment by ShivaniAjency** [comment]
noted
