### ISSUE TITLE
Why Bueno Finance: Incorrect tile width

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#9]
**Description:**
The tile width on the site is incorrect. The width on the site is 210.84px whereas in the design it is 206px.

**Screenshots:**
1) Design 

![image](https://user-images.githubusercontent.com/75774252/155708143-df4a1ca9-9cb4-4bd6-9d11-89139497469a.png)

2) Site

![image](https://user-images.githubusercontent.com/75774252/155708439-342ce86b-b52a-4c74-9e6b-ddd3908c305c.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency I have set the container width "auto" to align it with the main grid container. If we add fixed width it will not be responsive on smaller screens. 
![image](https://user-images.githubusercontent.com/81617777/156106681-f07d39cd-eb56-4567-8474-e87b96406a87.png)

**Comment by ShivaniAjency** [comment]
Noted
