### ISSUE TITLE
About us: The Team: Improper Space between the excerpt and team member column

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#90]
Description:
There is no space between the 'The Team' excerpt and the team member column

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157592836-b7581ca0-3edd-45db-8c9d-eb910a9ac1dd.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157592940-2df03055-8173-47a9-a072-a7957f37010f.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency this is a content change issue. The class got removed while changing the content.

**Comment by ShivaniAjency** [comment]
Noted. The issue is fixed
