### ISSUE TITLE
Career page: Why work @ Bueno Finance: Spacing issue

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#91]
Description:

- The featured image is touching the bottom of the container
- The icons and the end of the container have no proper spacing. 

screenshot:
Site
![image](https://user-images.githubusercontent.com/75774252/157594834-277a4046-b053-497b-8c1e-73d4da05ddec.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157594921-851fe47c-d8fb-458b-9f15-d480734426f4.png)

**Comment by ShivaniAjency** [comment]
The UI on MacBook Air safari 13.1 is broken
![Screenshot 2022-03-10 at 11 06 01 AM](https://user-images.githubusercontent.com/75774252/157596622-e78c1d5a-3260-4cdc-a9f0-2c19ac52f851.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency  It looks like the image is not loaded properly please reload try in incognito

**Comment by ShivaniAjency** [comment]
Issue fixed
