### ISSUE TITLE
Career: opportunities: accordion when closed: The text for development, type and field should be black 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#92]
Description:

The text on the accordion when closed should be black in color. Currently, they are green.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157596188-8975bbf6-4359-4ac5-9dbf-0a5c97e50f4f.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157596237-05871237-0e1f-4252-835e-cf2e1fa40b62.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Its black #000000

![image](https://user-images.githubusercontent.com/81617777/157596731-a577a77e-8a24-48be-8346-8bb4b75a5c87.png)

**Comment by ShivaniAjency** [comment]
noted
