### ISSUE TITLE
Career page: Post form submission: Unable to submit another form response

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/bueno-finance-new#99]
Description:

- After submitting the form, the form pop-up remains and one is unable to submit another response

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/157810356-fc95437c-42b9-4ec6-bdf4-222c129ab70e.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency after the successful form submit the popup will remain open to display the success message. If you want to submit another response please close the popup refresh the page & try to submit another response.

**Comment by ShivaniAjency** [comment]
Noted
